### ISSUE TITLE
null response for valid VRMs

### ISSUE THREAD

**Issue by harry-jones** [billinghamj/vrm-node#1]
Hi, thanks for creating this, it's great.

I'm having an issue with two VRMs (out of a dataset of ~10,000), where the info method is returning null, despite the VRMs being valid.

The two VRMs are `VIP1` and `Q362KUA`, both of which are registered vehicles in the UK. 

You can verify these vehicles are registered at https://vehicleenquiry.service.gov.uk/ (VIP1 is a Rolls Royce and Q362KUA is a Caterham).

Q362KUA is a Q registration number (see https://www.gov.uk/vehicle-registration/q-registration-numbers), but should match the `gb_1983` format.

VIP1 looks like the `gb_1932` format.

Do you know why these VRMs return null?

**Comment by billinghamj** [comment]
The reason both of these have been rejected is because the characters `Q` and `I` are prohibited in GB VRMs. This may need to be reconsidered however - let me just read up on the documentation.

Generally VRMs containing the characters `I` and `Z` are Irish.

We may have initially decided to ignore and reject `Q` plates for @cuvva's purposes, though I think they probably should be handled properly.

**Comment by billinghamj** [comment]
It is also worth noting that I believe the DVLA have not 100% consistently followed their own rules. It is my understanding that a very small number of VRMs do exist completely outside the allowed cases.

**Comment by billinghamj** [comment]
Another case is `IND1A` - though the plate is not currently registered, but has existed.

**Comment by billinghamj** [comment]
As per: http://www.cvpg.co.uk/REG.pdf

- `VIP1` would generally be `ni_1966` format, where the area code is `IP`. This would be Northern Irish because area codes containing an `I` or `Z` are Irish. However, `IP` is not on the list of known/existing area codes.
- `IND1A` would generally be `gb_1963`, where the area code is `ND` and the "serial letter" is `I`. This is currently excluded on the basis that serial letters cannot be `I`, `Q` or `Z`. I suspect that this constraint may not be correct, but I have not been able to find any evidence either way for this yet. 
- `Q362KUA` would generally be `gb_1983`, where the area code is `UA`, the serial letter is `K` and the year letter is `Q`. A year letter cannot be `Q` so this is currently rejected.

The `Q` case is fairly clearly defined and should be fixable by adding a new set of formats designed for them specifically.

I think we'd need to find some evidence/documentation to support the other two cases before implementing the changes. I am particularly concerned around ensuring the serial letters are not handled incorrectly.

The solution for the `VIP` plate may be to just change from having a specific predefined list of areas, to just ensuring that the area code contains a `Z` or an `I`. I recall that I did consider this early on, but did not pursue it. Will need to determine why not.

**Comment by billinghamj** [comment]
@harry-jones Would appreciate your feedback on my points before proceeding

**Comment by billinghamj** [comment]
Some useful info in relation to `VIP1`: https://en.wikipedia.org/wiki/Vehicle_registration_plates_of_the_United_Kingdom,_Crown_dependencies_and_overseas_territories#Other_registration_plates

**Comment by billinghamj** [comment]
https://en.wikipedia.org/wiki/Vehicle_registration_plates_of_the_United_Kingdom,_Crown_dependencies_and_overseas_territories#1932_to_1963

> I, Q, and Z were not used as serial letters, as the use of I and Z continued to be restricted to Ireland and Q was reserved for temporary imports

There is no mention of serial letters after this point, but the next few formats are all derivatives so one could reasonably assume that the same limitation applies

**Comment by harry-jones** [comment]
Very interesting on `VIP1`!

I think it would be useful to add the Republic of Ireland county codes (`IP` et al) to the pattern in order to accept these VRMs. The DVLA have historically issued registrations for these Irish counties so we must consider them valid. By adding the codes we still validate against input which has neither a valid Northern Irish or Republic of Ireland area code, and can continue to return the area code as metadata in the response. 

On `Q` plates I would defintely value having a format for these as they are acceptable for the project I am working on. It would then be useful to have a way when initialising the package to specify the formats you want to check against?

The `IND1A` example is frustrating as it certainly seems like the `I`, `Q`, `Z` serial restriction would have continued after 1963. Suggest we do more research and attenpt to find more examples before making a change here. 

Shall I make a pull request for either the `Q` format or the Irish counties? Happy to get involved, but don't want to step on your toes either :)

**Comment by billinghamj** [comment]
Okay, I think I'm going to allow any area code containing either an `I` or a `Z` for the `ni_` formats.

I'd appreciate it if you could make a PR for the `Q` formats. If there are multiple different formats by date, please make them as multiple files.

I will resolve the NI areas issue now, but I think the `IND1A` case will need to remain unresolved for now.

**Comment by billinghamj** [comment]
https://github.com/billinghamj/vrm-node/pull/2

**Comment by harry-jones** [comment]
Some interesting info about 'Q' plates here: http://nice-reg.co.uk/number-plates/number-plates/0-o-other-numbers-q.html

Also, have discovered the possibility of VRMs with a single letter Q(!) http://nice-reg.co.uk/number-plates/number-plates/0-1-one-letter-q.html

**Comment by billinghamj** [comment]
#2 is merged

**Comment by billinghamj** [comment]
Hmm most of those 'Q' plates followed by lots of numbers seem completely invalid imo

**Comment by billinghamj** [comment]
I'd suggest looking only at actual documentation supplied by somewhat knowledgeable bodies, rather than looking at registration plates which do exist - it isn't possible to validate every single plate in existence, because so many of them violate the rules.

**Comment by billinghamj** [comment]
Closing for now due to inactivity.
